/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ClPrice {
        /**
          * Sku code
         */
        "sku": string | undefined;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string | undefined;
        /**
          * The last name
         */
        "last": string | undefined;
        /**
          * The middle name
         */
        "middle": string | undefined;
    }
}
declare global {
    interface HTMLClPriceElement extends Components.ClPrice, HTMLStencilElement {
    }
    var HTMLClPriceElement: {
        prototype: HTMLClPriceElement;
        new (): HTMLClPriceElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cl-price": HTMLClPriceElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ClPrice {
        /**
          * Sku code
         */
        "sku"?: string | undefined;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string | undefined;
        /**
          * The last name
         */
        "last"?: string | undefined;
        /**
          * The middle name
         */
        "middle"?: string | undefined;
    }
    interface IntrinsicElements {
        "cl-price": ClPrice;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cl-price": LocalJSX.ClPrice & JSXBase.HTMLAttributes<HTMLClPriceElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
