/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ClAddToCart {
        /**
          * The SKU or bundle code (i.e. the unique identifier of the product or bundle you want to add to the shopping cart).
         */
        "code": string | undefined;
        /**
          * The frequency which generates a [subscription](https://docs.commercelayer.io/core/v/how-tos/placing-orders/subscriptions). The value must be supported by the associated subscription model.
         */
        "frequency": string | undefined;
        /**
          * A custom image URL for the product or bundle that will be added to the cart. If not provided, the image URL will be taken from the item being added.
         */
        "imageUrl": string | undefined;
        /**
          * Indicates whether the code refers to a `sku` or a `bundle`.
          * @default sku
         */
        "kind"?: "sku" | "bundle";
        /**
          * A custom name for the product or bundle that will be added to the cart. If not provided, the name will be taken from the item being added.
         */
        "name": string | undefined;
        /**
          * The number of units of the selected product you want to add to the shopping cart.
          * @default 1
         */
        "quantity": number;
    }
    interface ClAvailability {
        /**
          * The SKU or bundle code (i.e. the unique identifier of the product or bundle whose availability you want to display).
         */
        "code": string | undefined;
        /**
          * Indicates whether the code refers to a `sku` or a `bundle`.  _⚠️ `bundle` support is limited. The `cl-availability-info` component does not display availability information for bundles._
          * @default sku
         */
        "kind"?: "sku" | "bundle";
        /**
          * The rule used to determine the information that will be displayed. `cheapest` is the delivery lead time associated with the lower shipping method cost, `fastest` is the delivery lead time associated with the lower average time to delivery.
          * @default "cheapest"
         */
        "rule": "cheapest" | "fastest";
    }
    interface ClAvailabilityInfo {
        /**
          * The type of information to be displayed.
         */
        "type": | "min-days"
    | "max-days"
    | "min-hours"
    | "max-hours"
    | "shipping-method-name"
    | "shipping-method-price"
    | undefined;
    }
    interface ClAvailabilityStatus {
        /**
          * The product availability status. It determines the visibility of the inner message.
         */
        "type": | "available"
    | "available-with-info"
    | "unavailable"
    | undefined;
    }
    interface ClCart {
        /**
          * Indicate whether the minicart is open or not (available _only_ when the `cl-cart` component is used as _minicart_).
          * @default false
         */
        "open": boolean;
        /**
          * Open the minicart and set the opener so that the minicart can be closed by focusing on the opener. (available _only_ when the `cl-cart` component is used as _minicart_).
          * @param opener The opener of the minicart.
         */
        "openMinicart": (opener: Pick<HTMLElement, "focus">) => Promise<void>;
        /**
          * If `true` the minicart automatically opens as soon as an item is added to the shopping cart (available _only_ when the `cl-cart` component is used as _minicart_).
          * @default false
         */
        "openOnAdd": boolean;
        /**
          * By default the `cl-cart` is directly displayed in-place. Setting the `type` to `mini` will change the behavior to be a minicart.
         */
        "type": "mini" | undefined;
    }
    interface ClCartCount {
        /**
          * Toggle this switch to hide the counter when the cart is empty instead of showing `0`.
          * @default false
         */
        "hideWhenEmpty": boolean;
    }
    interface ClCartLink {
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target": "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClCheckoutLink {
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target": "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClIdentityInfo {
        /**
          * The field to be displayed.  Valid values are: - `"email"` - `"metadata.*"` (e.g. `"metadata.firstname"`, etc.)
         */
        "field": string;
    }
    interface ClIdentityLink {
        /**
          * Enable a custom reset password link visible on the login form page. When set, a "Forgot password?" link will be shown on the right below the Password field.
         */
        "resetPasswordUrl"?: string;
        /**
          * Your sales channel [scope](https://docs.commercelayer.io/core/authentication#authorization-scopes) (used to restrict the dataset of your application to a market and/or stock location). If specified, it will override the default scope set in the drop-in library configuration. Otherwise, the default scope taken from the drop-in library configuration will be used.
         */
        "scope"?: string;
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target": "_self" | "_blank" | "_parent" | "_top";
        /**
          * The user account access action.
         */
        "type": "login" | "signup" | "logout" | undefined;
    }
    interface ClIdentityStatus {
        /**
          * The user identity status (logged in or not logged in). It determines the visibility of the inner message based on the stored token.
         */
        "type": "guest" | "customer" | undefined;
    }
    interface ClMyAccountLink {
        /**
          * Providing this attribute will enable the "Back to shop" and "Logout" navigation links on the My Account page. When set to `true`, the link will redirect to the current page URL. You can also provide a custom URL string.
         */
        "backToShop"?: "true" | string;
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target": "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClPrice {
        /**
          * The SKU or bundle code (i.e. the unique identifier of the product or bundle whose price you want to display).
         */
        "code": string | undefined;
        /**
          * Indicates whether the code refers to a `sku` or a `bundle`.
          * @default sku
         */
        "kind"?: "sku" | "bundle";
    }
    interface ClPriceAmount {
        /**
          * The type of price amount to be displayed.
          * @default "price"
         */
        "type": "price" | "compare-at";
    }
}
declare global {
    interface HTMLClAddToCartElement extends Components.ClAddToCart, HTMLStencilElement {
    }
    var HTMLClAddToCartElement: {
        prototype: HTMLClAddToCartElement;
        new (): HTMLClAddToCartElement;
    };
    interface HTMLClAvailabilityElement extends Components.ClAvailability, HTMLStencilElement {
    }
    var HTMLClAvailabilityElement: {
        prototype: HTMLClAvailabilityElement;
        new (): HTMLClAvailabilityElement;
    };
    interface HTMLClAvailabilityInfoElement extends Components.ClAvailabilityInfo, HTMLStencilElement {
    }
    var HTMLClAvailabilityInfoElement: {
        prototype: HTMLClAvailabilityInfoElement;
        new (): HTMLClAvailabilityInfoElement;
    };
    interface HTMLClAvailabilityStatusElement extends Components.ClAvailabilityStatus, HTMLStencilElement {
    }
    var HTMLClAvailabilityStatusElement: {
        prototype: HTMLClAvailabilityStatusElement;
        new (): HTMLClAvailabilityStatusElement;
    };
    interface HTMLClCartElement extends Components.ClCart, HTMLStencilElement {
    }
    var HTMLClCartElement: {
        prototype: HTMLClCartElement;
        new (): HTMLClCartElement;
    };
    interface HTMLClCartCountElement extends Components.ClCartCount, HTMLStencilElement {
    }
    var HTMLClCartCountElement: {
        prototype: HTMLClCartCountElement;
        new (): HTMLClCartCountElement;
    };
    interface HTMLClCartLinkElement extends Components.ClCartLink, HTMLStencilElement {
    }
    var HTMLClCartLinkElement: {
        prototype: HTMLClCartLinkElement;
        new (): HTMLClCartLinkElement;
    };
    interface HTMLClCheckoutLinkElement extends Components.ClCheckoutLink, HTMLStencilElement {
    }
    var HTMLClCheckoutLinkElement: {
        prototype: HTMLClCheckoutLinkElement;
        new (): HTMLClCheckoutLinkElement;
    };
    interface HTMLClIdentityInfoElement extends Components.ClIdentityInfo, HTMLStencilElement {
    }
    var HTMLClIdentityInfoElement: {
        prototype: HTMLClIdentityInfoElement;
        new (): HTMLClIdentityInfoElement;
    };
    interface HTMLClIdentityLinkElement extends Components.ClIdentityLink, HTMLStencilElement {
    }
    var HTMLClIdentityLinkElement: {
        prototype: HTMLClIdentityLinkElement;
        new (): HTMLClIdentityLinkElement;
    };
    interface HTMLClIdentityStatusElement extends Components.ClIdentityStatus, HTMLStencilElement {
    }
    var HTMLClIdentityStatusElement: {
        prototype: HTMLClIdentityStatusElement;
        new (): HTMLClIdentityStatusElement;
    };
    interface HTMLClMyAccountLinkElement extends Components.ClMyAccountLink, HTMLStencilElement {
    }
    var HTMLClMyAccountLinkElement: {
        prototype: HTMLClMyAccountLinkElement;
        new (): HTMLClMyAccountLinkElement;
    };
    interface HTMLClPriceElement extends Components.ClPrice, HTMLStencilElement {
    }
    var HTMLClPriceElement: {
        prototype: HTMLClPriceElement;
        new (): HTMLClPriceElement;
    };
    interface HTMLClPriceAmountElement extends Components.ClPriceAmount, HTMLStencilElement {
    }
    var HTMLClPriceAmountElement: {
        prototype: HTMLClPriceAmountElement;
        new (): HTMLClPriceAmountElement;
    };
    interface HTMLElementTagNameMap {
        "cl-add-to-cart": HTMLClAddToCartElement;
        "cl-availability": HTMLClAvailabilityElement;
        "cl-availability-info": HTMLClAvailabilityInfoElement;
        "cl-availability-status": HTMLClAvailabilityStatusElement;
        "cl-cart": HTMLClCartElement;
        "cl-cart-count": HTMLClCartCountElement;
        "cl-cart-link": HTMLClCartLinkElement;
        "cl-checkout-link": HTMLClCheckoutLinkElement;
        "cl-identity-info": HTMLClIdentityInfoElement;
        "cl-identity-link": HTMLClIdentityLinkElement;
        "cl-identity-status": HTMLClIdentityStatusElement;
        "cl-my-account-link": HTMLClMyAccountLinkElement;
        "cl-price": HTMLClPriceElement;
        "cl-price-amount": HTMLClPriceAmountElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface ClAddToCart {
        /**
          * The SKU or bundle code (i.e. the unique identifier of the product or bundle you want to add to the shopping cart).
         */
        "code": string | undefined;
        /**
          * The frequency which generates a [subscription](https://docs.commercelayer.io/core/v/how-tos/placing-orders/subscriptions). The value must be supported by the associated subscription model.
         */
        "frequency"?: string | undefined;
        /**
          * A custom image URL for the product or bundle that will be added to the cart. If not provided, the image URL will be taken from the item being added.
         */
        "imageUrl"?: string | undefined;
        /**
          * Indicates whether the code refers to a `sku` or a `bundle`.
          * @default sku
         */
        "kind"?: "sku" | "bundle";
        /**
          * A custom name for the product or bundle that will be added to the cart. If not provided, the name will be taken from the item being added.
         */
        "name"?: string | undefined;
        /**
          * The number of units of the selected product you want to add to the shopping cart.
          * @default 1
         */
        "quantity"?: number;
    }
    interface ClAvailability {
        /**
          * The SKU or bundle code (i.e. the unique identifier of the product or bundle whose availability you want to display).
         */
        "code": string | undefined;
        /**
          * Indicates whether the code refers to a `sku` or a `bundle`.  _⚠️ `bundle` support is limited. The `cl-availability-info` component does not display availability information for bundles._
          * @default sku
         */
        "kind"?: "sku" | "bundle";
        /**
          * The rule used to determine the information that will be displayed. `cheapest` is the delivery lead time associated with the lower shipping method cost, `fastest` is the delivery lead time associated with the lower average time to delivery.
          * @default "cheapest"
         */
        "rule"?: "cheapest" | "fastest";
    }
    interface ClAvailabilityInfo {
        /**
          * The type of information to be displayed.
         */
        "type": | "min-days"
    | "max-days"
    | "min-hours"
    | "max-hours"
    | "shipping-method-name"
    | "shipping-method-price"
    | undefined;
    }
    interface ClAvailabilityStatus {
        /**
          * The product availability status. It determines the visibility of the inner message.
         */
        "type": | "available"
    | "available-with-info"
    | "unavailable"
    | undefined;
    }
    interface ClCart {
        /**
          * Indicate whether the minicart is open or not (available _only_ when the `cl-cart` component is used as _minicart_).
          * @default false
         */
        "open"?: boolean;
        /**
          * If `true` the minicart automatically opens as soon as an item is added to the shopping cart (available _only_ when the `cl-cart` component is used as _minicart_).
          * @default false
         */
        "openOnAdd"?: boolean;
        /**
          * By default the `cl-cart` is directly displayed in-place. Setting the `type` to `mini` will change the behavior to be a minicart.
         */
        "type"?: "mini" | undefined;
    }
    interface ClCartCount {
        /**
          * Toggle this switch to hide the counter when the cart is empty instead of showing `0`.
          * @default false
         */
        "hideWhenEmpty"?: boolean;
    }
    interface ClCartLink {
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target"?: "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClCheckoutLink {
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target"?: "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClIdentityInfo {
        /**
          * The field to be displayed.  Valid values are: - `"email"` - `"metadata.*"` (e.g. `"metadata.firstname"`, etc.)
         */
        "field": string;
    }
    interface ClIdentityLink {
        /**
          * Enable a custom reset password link visible on the login form page. When set, a "Forgot password?" link will be shown on the right below the Password field.
         */
        "resetPasswordUrl"?: string;
        /**
          * Your sales channel [scope](https://docs.commercelayer.io/core/authentication#authorization-scopes) (used to restrict the dataset of your application to a market and/or stock location). If specified, it will override the default scope set in the drop-in library configuration. Otherwise, the default scope taken from the drop-in library configuration will be used.
         */
        "scope"?: string;
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target"?: "_self" | "_blank" | "_parent" | "_top";
        /**
          * The user account access action.
         */
        "type": "login" | "signup" | "logout" | undefined;
    }
    interface ClIdentityStatus {
        /**
          * The user identity status (logged in or not logged in). It determines the visibility of the inner message based on the stored token.
         */
        "type": "guest" | "customer" | undefined;
    }
    interface ClMyAccountLink {
        /**
          * Providing this attribute will enable the "Back to shop" and "Logout" navigation links on the My Account page. When set to `true`, the link will redirect to the current page URL. You can also provide a custom URL string.
         */
        "backToShop"?: "true" | string;
        /**
          * The browsing context in which to open the linked URL (a tab, a window, or an &lt;iframe&gt;).
          * @default "_self"
         */
        "target"?: "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClPrice {
        /**
          * The SKU or bundle code (i.e. the unique identifier of the product or bundle whose price you want to display).
         */
        "code": string | undefined;
        /**
          * Indicates whether the code refers to a `sku` or a `bundle`.
          * @default sku
         */
        "kind"?: "sku" | "bundle";
    }
    interface ClPriceAmount {
        /**
          * The type of price amount to be displayed.
          * @default "price"
         */
        "type"?: "price" | "compare-at";
    }

    interface ClAddToCartAttributes {
        "kind": "sku" | "bundle";
        "code": string | undefined;
        "quantity": number;
        "name": string | undefined;
        "imageUrl": string | undefined;
        "frequency": string | undefined;
    }
    interface ClAvailabilityAttributes {
        "kind": "sku" | "bundle";
        "code": string | undefined;
        "rule": "cheapest" | "fastest";
    }
    interface ClAvailabilityInfoAttributes {
        "type": | "min-days"
    | "max-days"
    | "min-hours"
    | "max-hours"
    | "shipping-method-name"
    | "shipping-method-price"
    | undefined;
    }
    interface ClAvailabilityStatusAttributes {
        "type": | "available"
    | "available-with-info"
    | "unavailable"
    | undefined;
    }
    interface ClCartAttributes {
        "type": "mini" | undefined;
        "openOnAdd": boolean;
        "open": boolean;
    }
    interface ClCartCountAttributes {
        "hideWhenEmpty": boolean;
    }
    interface ClCartLinkAttributes {
        "target": "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClCheckoutLinkAttributes {
        "target": "_self" | "_blank" | "_parent" | "_top";
    }
    interface ClIdentityInfoAttributes {
        "field": string;
    }
    interface ClIdentityLinkAttributes {
        "target": "_self" | "_blank" | "_parent" | "_top";
        "type": "login" | "signup" | "logout" | undefined;
        "resetPasswordUrl": string;
        "scope": string;
    }
    interface ClIdentityStatusAttributes {
        "type": "guest" | "customer" | undefined;
    }
    interface ClMyAccountLinkAttributes {
        "target": "_self" | "_blank" | "_parent" | "_top";
        "backToShop": "true" | string;
    }
    interface ClPriceAttributes {
        "kind": "sku" | "bundle";
        "code": string | undefined;
    }
    interface ClPriceAmountAttributes {
        "type": "price" | "compare-at";
    }

    interface IntrinsicElements {
        "cl-add-to-cart": Omit<ClAddToCart, keyof ClAddToCartAttributes> & { [K in keyof ClAddToCart & keyof ClAddToCartAttributes]?: ClAddToCart[K] } & { [K in keyof ClAddToCart & keyof ClAddToCartAttributes as `attr:${K}`]?: ClAddToCartAttributes[K] } & { [K in keyof ClAddToCart & keyof ClAddToCartAttributes as `prop:${K}`]?: ClAddToCart[K] } & OneOf<"code", ClAddToCart["code"], ClAddToCartAttributes["code"]>;
        "cl-availability": Omit<ClAvailability, keyof ClAvailabilityAttributes> & { [K in keyof ClAvailability & keyof ClAvailabilityAttributes]?: ClAvailability[K] } & { [K in keyof ClAvailability & keyof ClAvailabilityAttributes as `attr:${K}`]?: ClAvailabilityAttributes[K] } & { [K in keyof ClAvailability & keyof ClAvailabilityAttributes as `prop:${K}`]?: ClAvailability[K] } & OneOf<"code", ClAvailability["code"], ClAvailabilityAttributes["code"]>;
        "cl-availability-info": Omit<ClAvailabilityInfo, keyof ClAvailabilityInfoAttributes> & { [K in keyof ClAvailabilityInfo & keyof ClAvailabilityInfoAttributes]?: ClAvailabilityInfo[K] } & { [K in keyof ClAvailabilityInfo & keyof ClAvailabilityInfoAttributes as `attr:${K}`]?: ClAvailabilityInfoAttributes[K] } & { [K in keyof ClAvailabilityInfo & keyof ClAvailabilityInfoAttributes as `prop:${K}`]?: ClAvailabilityInfo[K] } & OneOf<"type", ClAvailabilityInfo["type"], ClAvailabilityInfoAttributes["type"]>;
        "cl-availability-status": Omit<ClAvailabilityStatus, keyof ClAvailabilityStatusAttributes> & { [K in keyof ClAvailabilityStatus & keyof ClAvailabilityStatusAttributes]?: ClAvailabilityStatus[K] } & { [K in keyof ClAvailabilityStatus & keyof ClAvailabilityStatusAttributes as `attr:${K}`]?: ClAvailabilityStatusAttributes[K] } & { [K in keyof ClAvailabilityStatus & keyof ClAvailabilityStatusAttributes as `prop:${K}`]?: ClAvailabilityStatus[K] } & OneOf<"type", ClAvailabilityStatus["type"], ClAvailabilityStatusAttributes["type"]>;
        "cl-cart": Omit<ClCart, keyof ClCartAttributes> & { [K in keyof ClCart & keyof ClCartAttributes]?: ClCart[K] } & { [K in keyof ClCart & keyof ClCartAttributes as `attr:${K}`]?: ClCartAttributes[K] } & { [K in keyof ClCart & keyof ClCartAttributes as `prop:${K}`]?: ClCart[K] };
        "cl-cart-count": Omit<ClCartCount, keyof ClCartCountAttributes> & { [K in keyof ClCartCount & keyof ClCartCountAttributes]?: ClCartCount[K] } & { [K in keyof ClCartCount & keyof ClCartCountAttributes as `attr:${K}`]?: ClCartCountAttributes[K] } & { [K in keyof ClCartCount & keyof ClCartCountAttributes as `prop:${K}`]?: ClCartCount[K] };
        "cl-cart-link": Omit<ClCartLink, keyof ClCartLinkAttributes> & { [K in keyof ClCartLink & keyof ClCartLinkAttributes]?: ClCartLink[K] } & { [K in keyof ClCartLink & keyof ClCartLinkAttributes as `attr:${K}`]?: ClCartLinkAttributes[K] } & { [K in keyof ClCartLink & keyof ClCartLinkAttributes as `prop:${K}`]?: ClCartLink[K] };
        "cl-checkout-link": Omit<ClCheckoutLink, keyof ClCheckoutLinkAttributes> & { [K in keyof ClCheckoutLink & keyof ClCheckoutLinkAttributes]?: ClCheckoutLink[K] } & { [K in keyof ClCheckoutLink & keyof ClCheckoutLinkAttributes as `attr:${K}`]?: ClCheckoutLinkAttributes[K] } & { [K in keyof ClCheckoutLink & keyof ClCheckoutLinkAttributes as `prop:${K}`]?: ClCheckoutLink[K] };
        "cl-identity-info": Omit<ClIdentityInfo, keyof ClIdentityInfoAttributes> & { [K in keyof ClIdentityInfo & keyof ClIdentityInfoAttributes]?: ClIdentityInfo[K] } & { [K in keyof ClIdentityInfo & keyof ClIdentityInfoAttributes as `attr:${K}`]?: ClIdentityInfoAttributes[K] } & { [K in keyof ClIdentityInfo & keyof ClIdentityInfoAttributes as `prop:${K}`]?: ClIdentityInfo[K] } & OneOf<"field", ClIdentityInfo["field"], ClIdentityInfoAttributes["field"]>;
        "cl-identity-link": Omit<ClIdentityLink, keyof ClIdentityLinkAttributes> & { [K in keyof ClIdentityLink & keyof ClIdentityLinkAttributes]?: ClIdentityLink[K] } & { [K in keyof ClIdentityLink & keyof ClIdentityLinkAttributes as `attr:${K}`]?: ClIdentityLinkAttributes[K] } & { [K in keyof ClIdentityLink & keyof ClIdentityLinkAttributes as `prop:${K}`]?: ClIdentityLink[K] } & OneOf<"type", ClIdentityLink["type"], ClIdentityLinkAttributes["type"]>;
        "cl-identity-status": Omit<ClIdentityStatus, keyof ClIdentityStatusAttributes> & { [K in keyof ClIdentityStatus & keyof ClIdentityStatusAttributes]?: ClIdentityStatus[K] } & { [K in keyof ClIdentityStatus & keyof ClIdentityStatusAttributes as `attr:${K}`]?: ClIdentityStatusAttributes[K] } & { [K in keyof ClIdentityStatus & keyof ClIdentityStatusAttributes as `prop:${K}`]?: ClIdentityStatus[K] } & OneOf<"type", ClIdentityStatus["type"], ClIdentityStatusAttributes["type"]>;
        "cl-my-account-link": Omit<ClMyAccountLink, keyof ClMyAccountLinkAttributes> & { [K in keyof ClMyAccountLink & keyof ClMyAccountLinkAttributes]?: ClMyAccountLink[K] } & { [K in keyof ClMyAccountLink & keyof ClMyAccountLinkAttributes as `attr:${K}`]?: ClMyAccountLinkAttributes[K] } & { [K in keyof ClMyAccountLink & keyof ClMyAccountLinkAttributes as `prop:${K}`]?: ClMyAccountLink[K] };
        "cl-price": Omit<ClPrice, keyof ClPriceAttributes> & { [K in keyof ClPrice & keyof ClPriceAttributes]?: ClPrice[K] } & { [K in keyof ClPrice & keyof ClPriceAttributes as `attr:${K}`]?: ClPriceAttributes[K] } & { [K in keyof ClPrice & keyof ClPriceAttributes as `prop:${K}`]?: ClPrice[K] } & OneOf<"code", ClPrice["code"], ClPriceAttributes["code"]>;
        "cl-price-amount": Omit<ClPriceAmount, keyof ClPriceAmountAttributes> & { [K in keyof ClPriceAmount & keyof ClPriceAmountAttributes]?: ClPriceAmount[K] } & { [K in keyof ClPriceAmount & keyof ClPriceAmountAttributes as `attr:${K}`]?: ClPriceAmountAttributes[K] } & { [K in keyof ClPriceAmount & keyof ClPriceAmountAttributes as `prop:${K}`]?: ClPriceAmount[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cl-add-to-cart": LocalJSX.IntrinsicElements["cl-add-to-cart"] & JSXBase.HTMLAttributes<HTMLClAddToCartElement>;
            "cl-availability": LocalJSX.IntrinsicElements["cl-availability"] & JSXBase.HTMLAttributes<HTMLClAvailabilityElement>;
            "cl-availability-info": LocalJSX.IntrinsicElements["cl-availability-info"] & JSXBase.HTMLAttributes<HTMLClAvailabilityInfoElement>;
            "cl-availability-status": LocalJSX.IntrinsicElements["cl-availability-status"] & JSXBase.HTMLAttributes<HTMLClAvailabilityStatusElement>;
            "cl-cart": LocalJSX.IntrinsicElements["cl-cart"] & JSXBase.HTMLAttributes<HTMLClCartElement>;
            "cl-cart-count": LocalJSX.IntrinsicElements["cl-cart-count"] & JSXBase.HTMLAttributes<HTMLClCartCountElement>;
            "cl-cart-link": LocalJSX.IntrinsicElements["cl-cart-link"] & JSXBase.HTMLAttributes<HTMLClCartLinkElement>;
            "cl-checkout-link": LocalJSX.IntrinsicElements["cl-checkout-link"] & JSXBase.HTMLAttributes<HTMLClCheckoutLinkElement>;
            "cl-identity-info": LocalJSX.IntrinsicElements["cl-identity-info"] & JSXBase.HTMLAttributes<HTMLClIdentityInfoElement>;
            "cl-identity-link": LocalJSX.IntrinsicElements["cl-identity-link"] & JSXBase.HTMLAttributes<HTMLClIdentityLinkElement>;
            "cl-identity-status": LocalJSX.IntrinsicElements["cl-identity-status"] & JSXBase.HTMLAttributes<HTMLClIdentityStatusElement>;
            "cl-my-account-link": LocalJSX.IntrinsicElements["cl-my-account-link"] & JSXBase.HTMLAttributes<HTMLClMyAccountLinkElement>;
            "cl-price": LocalJSX.IntrinsicElements["cl-price"] & JSXBase.HTMLAttributes<HTMLClPriceElement>;
            "cl-price-amount": LocalJSX.IntrinsicElements["cl-price-amount"] & JSXBase.HTMLAttributes<HTMLClPriceAmountElement>;
        }
    }
}
