name: Reset organization

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  reset_stock_items:
    name: Reset stock_items
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Node 🧰
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install 📦
        run: |
          npm install -g @commercelayer/cli
          commercelayer plugins:install seeder && exit 0
          exit 0

      - name: Login 🔑
        run: |
          commercelayer applications:login \
            --clientId ${{ secrets.CL_CLIENT_ID }} \
            --clientSecret ${{ secrets.CL_CLIENT_SECRET }} \
            --organization ${{ secrets.CL_ORGANIZATION }} \
            -d ${{ secrets.CL_DOMAIN }} \
            --alias cli-admin

      - name: Log 🔎
        run: |
          commercelayer version
          commercelayer plugins
          commercelayer applications:current

      - name: Seed 🌱
        run: commercelayer seeder:seed -b custom -n reset_stock_items -u ./packages/drop-in/seed

      # - name: Delete Addresses 🗑️
      #   uses: ./.github/actions/delete-addresses
      #   with:
      #     clientId: ${{ secrets.CL_CLIENT_ID }}
      #     clientSecret: ${{ secrets.CL_CLIENT_SECRET }}
      #     domain: ${{ secrets.CL_DOMAIN }}
