name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: pnpm 🧰
        uses: pnpm/action-setup@v5
        with:
          version: 10.4.0

      - name: Node 🧰
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install 📦
        run: pnpm install

      - name: TS Check 🔎
        run: pnpm ts:check

      - name: Lint 🔎
        run: pnpm lint

      - name: Run Audit 🔬
        run: pnpm audit || exit 0

      - name: Test 🐛
        run: pnpm test:unit

      - name: Build 🛠
        run: pnpm build
